services:
  - type: web
    name: telegram-views-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python viewsbot.py
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PORT
        value: 10000
    plan: free 
